branch-defaults:
  default:
    environment: producao
environment-defaults:
  producao:
    branch: null
    repository: null
global:
  application_name: smart-cleaner-api
  default_ec2_keyname: vockey
  default_platform: Docker
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: LabInstanceProfile
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
