name: smart-cleaner-api-pipeline
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.22.2
    - run: go mod vendor
    - run: CGO_ENABLED=0 GOOS=linux go build -mod=vendor -o "dist/main"
    - run: docker build -t smart-cleaner-api .
    - uses: actions/upload-artifact@v3
      with:
        name: smart-cleaner-api
        path: dist/
