name: smart-cleaner-api-pipeline
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker build -t smart-cleaner-api .
    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: images
